### ISSUE TITLE
Access to raw Count Matrix

### ISSUE THREAD

**Issue by zakiF** [qinzhu/VisCello.eht#1]
Hi Qin Zhu,

The [shiny](https://cello.shinyapps.io/sceht/) is a very nice tool to explore the data, as you mentioned some genes have been excluded due to server limitation. Wondering how can I go about to download the raw count data? The  [GSE137116](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137116) link points to a file called 'GSE137116_gene_by_cell_count_matrix.txt.gz' but it seems to only have three collumns? I was expecting this to be a genes x cell matrix? 

Most appreciated if you could advice a way to obtain the raw count data?

Best
Zaki

**Comment by qinzhu** [comment]
Hi,
The data deposited to GEO is in sparse matrix format. You can read in via the readMM function in R. The VisCello.eht package here also allow visualization of all the expressed gene.

**Comment by zakiF** [comment]
Thanks Qin Zhu, managed to load it into R
