### ISSUE TITLE
Contact for Information Sharing about This project

### ISSUE THREAD

**Issue by FizzerYu** [qinzhu/VisCello.eht#2]
We have a little problem to run this code, it seems that VisCello package could not be install properly.

So we may think could you update the cluster assignment on this repository. And we would also be grateful if you could also send us the low dimensional visualization coordinates (t-SNE etc)

**Comment by qinzhu** [comment]
Can you post the error message during install?

**Comment by FizzerYu** [comment]
Thank you, I have finish this problem. So I closed this issue.

Best
