### ISSUE TITLE
some questions about the access to data

### ISSUE THREAD

**Issue by July233** [qinzhu/VisCello.eht#3]
I want to use scATAT and scRNA seq data of tihis article (Developmental trajectory of pre-hematopoietic stem cell formation from endothelium),but I don't find the count matrix of  scATAT and scRNA seq data.
I need some helo about it,Thanks

**Comment by qinzhu** [comment]
Please check https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137116 for scRNA data and https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137115 for scATAC data.

**Comment by July233** [comment]
因为想用文献中提到的seruat方法，但是geo数据库补充信息给的数据不是count matrix。所以就来问一下只能下载sra数据然后分析吗？后续会在geo补充metrix矩阵吗。-------- 原始邮件 --------发件人： Qin Zhu <notifications@github.com>日期： 2020年6月29日周一 凌晨2:35收件人： "qinzhu/VisCello.eht" <VisCello.eht@noreply.github.com>抄送： July233 <xiaoyannuonuo@163.com>, Author <author@noreply.github.com>主    题： Re: [qinzhu/VisCello.eht] some questions about the access to data (#3)
Please check https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137116 for scRNA data and https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE137115 for scATAC data.

**Comment by qinzhu** [comment]
GEO的Supplementary file是有矩阵和meta data的啊
![image](https://user-images.githubusercontent.com/10772232/85958791-311cdf80-b966-11ea-89b2-070ed2eece43.png)

**Comment by qinzhu** [comment]
Matrix is saved as sparse matrix format, you can read in via Matrix package in R, basically the readMM function.

**Comment by July233** [comment]
谢谢师兄，我初次探索这种数据，搞了乌龙。我晓得啦-------- 原始邮件 --------发件人： Qin Zhu <notifications@github.com>日期： 2020年6月29日周一 清晨5:39收件人： "qinzhu/VisCello.eht" <VisCello.eht@noreply.github.com>抄送： July233 <xiaoyannuonuo@163.com>, Author <author@noreply.github.com>主    题： Re: [qinzhu/VisCello.eht] some questions about the access to data (#3)

GEO的Supplementary file是有矩阵和meta data的啊

**Comment by qinzhu** [comment]
不客气！

**Comment by July233** [comment]
很抱歉又来打扰，因为自己的课题很需要把ATAC数据和RNA数据联合起来分析，所以很想用文献里的数据。
按照文献中的参考采用seraut算法，但是数据量过大，跑不出来，急死了。
所以请问在处理数据时，文献中所说的DAP，VEG意思是先对数据筛选一下得到DAP * cell matrix和VEG * cell matrix矩阵吗？然后再用seraut的方法进行co-emmeding分析吗？
谢谢解答
谢谢师兄，我初次探索这种数据，搞了乌龙。我晓得啦





-------- 原始邮件 --------
发件人： Qin Zhu <notifications@github.com>
日期： 2020年6月29日周一 清晨5:39
收件人： "qinzhu/VisCello.eht" <VisCello.eht@noreply.github.com>
抄送： July233 <xiaoyannuonuo@163.com>, Author <author@noreply.github.com>
主 题： Re: [qinzhu/VisCello.eht] some questions about the access to data
(#3)


GEO的Supplementary file是有矩阵和meta data的啊

**Comment by qinzhu** [comment]
DAP-DEG的方法思路是，你先对ATAC找cluster specific DAP，再对RNA找cluster specific DEG，再把两者对应起来。如果cluster 对应，那么它的DAP应该在DEG附近（genomic location）有很显著的enrichment。 这样你就得到了cluster level的ATAC和RNA的对应关系。然后你对每一组对应的cluster里面的每一个DEG，把对应的DAP的signal加起来，就得到一个DEG cis-activity matrix.这个东西就可以替换Seurat 里面的activity matrix. 我match DAP DEG的code在这里https://github.com/qinzhu/eht_custom_analysis_function/blob/master/dap_deg_matching.R 不过一直没时间好好annotate。你可以参考一下。另外Seurat本身好像就确实慢，即使用DAP-DEG也不一定会加快很多... Good luck!

**Comment by July233** [comment]
求助！我在用signac分析ATAC这部分数据，ATAC的数据要包含fragments.tsv.gz and fragments.tsv.gz.tbi 

在补充数据中是只有GSE137115_peak_annotation.csv.gz文件，因此annoations过程一直失败

是否可补充fragments file index文件，好像cellranger跑出来会给两个文件的










在 2020-11-15 03:14:37，"Qin Zhu" <notifications@github.com> 写道：

DAP-DEG的方法思路是，你先对ATAC找cluster specific DAP，再对RNA找cluster specific DEG，再把两者对应起来。如果cluster 对应，那么它的DAP应该在DEG附近（genomic location）有很显著的enrichment。 这样你就得到了cluster level的ATAC和RNA的对应关系。然后你对每一组对应的cluster里面的每一个DEG，把对应的DAP的signal加起来，就得到一个DEG cis-activity matrix.这个东西就可以替换Seurat 里面的activity matrix. 我match DAP DEG的code在这里https://github.com/qinzhu/eht_custom_analysis_function/blob/master/dap_deg_matching.R 不过一直没时间好好annotate。你可以参考一下。另外Seurat本身好像就确实慢，即使用DAP-DEG也不一定会加快很多... Good luck!

**Comment by July233** [comment]
很想问大佬注释scATAC-seq是用的什么方法呢，就是把peaks变成gene..

貌似我遇到的问题就是这个东西....如果觉得此问题很简单就告诉我一下呜呜，我没搞明白谢谢您







求助！我在用signac分析ATAC这部分数据，ATAC的数据要包含fragments.tsv.gz and fragments.tsv.gz.tbi 

在补充数据中是只有GSE137115_peak_annotation.csv.gz文件，因此annoations过程一直失败

是否可补充fragments file index文件，好像cellranger跑出来会给两个文件的










在 2020-11-15 03:14:37，"Qin Zhu" <notifications@github.com> 写道：

DAP-DEG的方法思路是，你先对ATAC找cluster specific DAP，再对RNA找cluster specific DEG，再把两者对应起来。如果cluster 对应，那么它的DAP应该在DEG附近（genomic location）有很显著的enrichment。 这样你就得到了cluster level的ATAC和RNA的对应关系。然后你对每一组对应的cluster里面的每一个DEG，把对应的DAP的signal加起来，就得到一个DEG cis-activity matrix.这个东西就可以替换Seurat 里面的activity matrix. 我match DAP DEG的code在这里https://github.com/qinzhu/eht_custom_analysis_function/blob/master/dap_deg_matching.R 不过一直没时间好好annotate。你可以参考一下。另外Seurat本身好像就确实慢，即使用DAP-DEG也不一定会加快很多... Good luck!

**Comment by July233** [comment]
之前问的问题解决了，请问该篇文献的补充信息在哪里找呢😰只看到正文没有补充信息-------- 原始邮件 --------发件人： 闫诗宇 <15210018963@163.com>日期： 2020年11月16日周一 下午2:38收件人： "qinzhu/VisCello.eht" <reply@reply.github.com>主    题： Re:Re: [qinzhu/VisCello.eht] some questions about the access to data (#3)求助！我在用signac分析ATAC这部分数据，ATAC的数据要包含fragments.tsv.gz and fragments.tsv.gz.tbi 在补充数据中是只有GSE137115_peak_annotation.csv.gz文件，因此annoations过程一直失败是否可补充fragments file index文件，好像cellranger跑出来会给两个文件的在 2020-11-15 03:14:37，"Qin Zhu" <notifications@github.com> 写道：
DAP-DEG的方法思路是，你先对ATAC找cluster specific DAP，再对RNA找cluster specific DEG，再把两者对应起来。如果cluster 对应，那么它的DAP应该在DEG附近（genomic location）有很显著的enrichment。 这样你就得到了cluster level的ATAC和RNA的对应关系。然后你对每一组对应的cluster里面的每一个DEG，把对应的DAP的signal加起来，就得到一个DEG cis-activity matrix.这个东西就可以替换Seurat 里面的activity matrix. 我match DAP DEG的code在这里https://github.com/qinzhu/eht_custom_analysis_function/blob/master/dap_deg_matching.R 不过一直没时间好好annotate。你可以参考一下。另外Seurat本身好像就确实慢，即使用DAP-DEG也不一定会加快很多... Good luck!

**Comment by qinzhu** [comment]
https://doi.org/10.1182/blood.2020004801 页面拉到最后

**Comment by July233** [comment]
en....我打不开这个界面，要花100美元，钱太多了，能发一份文件给我吗。。
抱歉，我让国外的同学打开这个网站也要花钱。。













在 2020-11-28 22:46:23，"Qin Zhu" <notifications@github.com> 写道：

https://doi.org/10.1182/blood.2020004801 页面拉到最后

**Comment by qinzhu** [comment]
给我一下你的邮件，我传你

**Comment by July233** [comment]
xiaoyannuonuo@163.com谢谢-------- 原始邮件 --------发件人： Qin Zhu <notifications@github.com>日期： 2020年11月29日周日 晚上10:39收件人： "qinzhu/VisCello.eht" <VisCello.eht@noreply.github.com>抄送： July233 <xiaoyannuonuo@163.com>, Author <author@noreply.github.com>主    题： Re: [qinzhu/VisCello.eht] some questions about the access to data (#3)

给我一下你的邮件，我传你

**Comment by July233** [comment]
可能我们学校没有这个blood网页的版权…hhh。
感谢回复hhh

发件人: Qin Zhu
发送时间: 2020年11月28日 23:46
收件人: qinzhu/VisCello.eht
抄送: July233; Author
主题: Re: [qinzhu/VisCello.eht] some questions about the access to data(#3)

https://doi.org/10.1182/blood.2020004801 页面拉到最后

**Comment by Nidane** [comment]
想问一下没有fragments.tsv.gz.tbi 这个文件的话，最后可以怎么样实现annotation？谢谢
